<?php

  function dna_menu() {
    $items['dna'] = array(
      'title' => 'DNA',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('dna_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );
    $items['dna_success'] = array(
      'title' => 'DNA Helix',
      'page callback' => 'dna_result',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    return $items;
  }

  function dna_form() {
    $form['dna_input'] = array(
        '#title' => 'One half of DNA helix',
        '#type' => 'textfield',
        '#description' => t('Enter one half of the DNA helix'),
        '#element_validate' => array('element_validate_dna'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );
    return $form;
  }

  function element_validate_dna($element) {
    //Takes user inputted string and turns it into an array of upper case letters
    $input_dna = $element['#value'];
    $input_dna = strtoupper(str_replace(' ', '', $input_dna));
    $input_dna_array = str_split($input_dna);
    $dna_letters = array("A", "T", "C", "G");
    //Compares each inputted letter to the dna letters and returns an error if any inputted letter is not A T C or G
    foreach($input_dna_array as $letter) {
      if(!(in_array($letter, $dna_letters))) {
        form_error($element, t("Please enter only nucleotides A, T, C, and G"));
      }
    }
  }

  function dna_form_submit($form, &$form_state) {
    //Takes user inputted string and turns it into an array of upper case letters
    $user_input_dna = $form_state['values']['dna_input'];
    $user_input_dna = strtoupper(str_replace(' ', '', $user_input_dna));
    $user_input_dna_array = str_split($user_input_dna);
    //Sends user inputted array to dna_helix function
    $output_dna = dna_helix($user_input_dna_array);

    $_SESSION['input_dna'] = implode(" ", $user_input_dna_array);
    $_SESSION['output_dna'] = $output_dna;
    $form_state['redirect'] = 'dna_success';
  }

  function dna_helix($input_array) {
    $output_helix = [];
    //Checks each letter in the input array and push its corresponding nucleotide to an output array
    foreach($input_array as $dna_letter) {
      if($dna_letter === "A") {
        array_push($output_helix, "T");
      } elseif($dna_letter === "T") {
        array_push($output_helix, "A");
      } elseif($dna_letter === "C") {
        array_push($output_helix, "G");
      } else {
        array_push($output_helix, "C");
      }
    }
    //Returns the output helix as a string with a space between each letter
    return implode(" ", $output_helix);
  }

  function dna_result() {
    $input_dna_string = $_SESSION['input_dna'];
    $output_dna_string = $_SESSION['output_dna'];
    return "<p>The helix you inputted: $input_dna_string</p><p>The other helix to match: $output_dna_string</p>";
  }
